TSE Review - rspec
carlosveigadev/enumerables-ruby pull request #3
Opened 2020-08-11 21:33 UTC by wrakc

- We created specified tests using rspec gem for the following methods:
```
#my_each;
#my_each_with_index;
#my_select;
#my_all?;
#my_any;
#my_none;
#my_count;
#my_map;
#my_inject;
```

2020-08-12 11:51 UTC, lekegitrepo requested changes
### Status: Request changes :recycle: 
### Hi @wrakc and @jacobo12montes :clap: :clap:
#### You have done a good job :+1: However two test cases are still failing.

**_Remove files that are not related (.vscode)_** 

**_Fix these and submit them for review._**

#### Check my comments below about the failing test cases.

#### _Reviewed by Temitayo Adeleke._

2020-08-12 11:51 UTC, lekegitrepo commented on test.rb
> +puts ary.my_count{ |x| x%2==0 } #=> 3
**_#my_count counts the number of items in enum that are equal to an item if an argument is given_**

2020-08-12 11:51 UTC, lekegitrepo commented on test.rb
> +puts (5..10).my_inject(2) { |product, n| product * n } #=> 151200
**_#my_inject should raise a "LocalJumpError" when no block or argument is given_**

2020-08-12 17:01 UTC, wrakc commented
@lekegitrepo thanks for the feedback, we improved the code as suggested.
- Removed unnecessary files;
- Added test to raise LocalJumpError to my_inject.

2020-08-13 03:31 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @wrakc @jacobo12montes** 
Good job with your new submission for this project :muscle:  :muscle:
Your tests passes most of the requirements :clap: :clap: :clap:  
There are just a couple of details to improve before you can go ahead, please check out below the comments to your code.

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-08-13 03:31 UTC, andresporras3423 commented on spec/main_spec.rb
> +    it 'when an array is nill or false, and no block is given, should return true because there is nothing to compare with the array' do
replace "nill" with "nil"

2020-08-13 03:31 UTC, andresporras3423 commented on spec/main_spec.rb
> +      expect(array_words.my_all? { |word| word.length >= 3 }).to eql(true)
Test some negative scenarios using to_not eq:
### Example
`expect(array_words.my_all? { |word| word.length >= 3 }).to eql(true)`
`expect(array_words.my_all? { |word| word.length >= 3 }).to_not eql(false)`

2020-08-13 14:59 UTC, jacobo12montes commented
@andresporras3423 we made the improvements requested:
-Fix some typos
-Add  negative tests to the spec file

2020-08-14 04:31 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @wrakc @jacobo12montes** 
Great job following the improvements of the last review :muscle:  :muscle: 
We still need to fix one last detail:
- [ ] I have noticed you modified the rubocop default configuration. You should use the original configuration.

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-08-14 14:52 UTC, wrakc commented
Thanks, @andresporras3423, we improved the code as suggested:
- Added original rubocop .yml configuration.
- Fix rubocop offenses on rspecs files.

2020-08-14 21:40 UTC, krys2fa commented
# Status: Project Approved! 🥇 
Congratulations on making all the requested changes and getting this project approved. 👍 

You can now merge this branch into the master branch and go on with your next project.

💡  Do not forget to submit your project completion form after merging this branch.

All the best team,
Chris

2020-08-14 23:56 UTC, merged